# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cluster import task_pb2 as cluster_dot_task__pb2
from jobmanager import status_pb2 as jobmanager_dot_status__pb2
from jobmanager import resource_pb2 as jobmanager_dot_resource__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cluster/cluster_service.proto',
  package='grpc.cluster',
  syntax='proto3',
  serialized_pb=_b('\n\x1d\x63luster/cluster_service.proto\x12\x0cgrpc.cluster\x1a\x12\x63luster/task.proto\x1a\x17jobmanager/status.proto\x1a\x19jobmanager/resource.proto\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\t\"$\n\x12GetResourceRequest\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x08\">\n\x12SubmitTaskResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x18\n\x10internal_task_id\x18\x02 \x01(\t\"@\n\x11GetStatusResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x0b\n\x03log\x18\x03 \x01(\t\"S\n\x13GetResourceResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12,\n\tresources\x18\x02 \x03(\x0b\x32\x19.grpc.jobmanager.Resource2\xa6\x02\n\x0c\x43lusterProxy\x12R\n\x0bGetResource\x12 .grpc.cluster.GetResourceRequest\x1a!.grpc.cluster.GetResourceResponse\x12\x42\n\nSubmitTask\x12\x12.grpc.cluster.Task\x1a .grpc.cluster.SubmitTaskResponse\x12\x39\n\x08KillTask\x12\x15.grpc.cluster.Request\x1a\x16.grpc.cluster.Response\x12\x43\n\tGetStatus\x12\x15.grpc.cluster.Request\x1a\x1f.grpc.cluster.GetStatusResponseB\x1d\xaa\x02\x1aMicrosoft.CGC.GRPC.Clusterb\x06proto3')
  ,
  dependencies=[cluster_dot_task__pb2.DESCRIPTOR,jobmanager_dot_status__pb2.DESCRIPTOR,jobmanager_dot_resource__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='grpc.cluster.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.cluster.Request.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=140,
)


_GETRESOURCEREQUEST = _descriptor.Descriptor(
  name='GetResourceRequest',
  full_name='grpc.cluster.GetResourceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='grpc.cluster.GetResourceRequest.config', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=178,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='grpc.cluster.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc.cluster.Response.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=206,
)


_SUBMITTASKRESPONSE = _descriptor.Descriptor(
  name='SubmitTaskResponse',
  full_name='grpc.cluster.SubmitTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc.cluster.SubmitTaskResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='internal_task_id', full_name='grpc.cluster.SubmitTaskResponse.internal_task_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=270,
)


_GETSTATUSRESPONSE = _descriptor.Descriptor(
  name='GetStatusResponse',
  full_name='grpc.cluster.GetStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc.cluster.GetStatusResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='grpc.cluster.GetStatusResponse.status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log', full_name='grpc.cluster.GetStatusResponse.log', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=336,
)


_GETRESOURCERESPONSE = _descriptor.Descriptor(
  name='GetResourceResponse',
  full_name='grpc.cluster.GetResourceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='grpc.cluster.GetResourceResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resources', full_name='grpc.cluster.GetResourceResponse.resources', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=421,
)

_GETRESOURCERESPONSE.fields_by_name['resources'].message_type = jobmanager_dot_resource__pb2._RESOURCE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['GetResourceRequest'] = _GETRESOURCEREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['SubmitTaskResponse'] = _SUBMITTASKRESPONSE
DESCRIPTOR.message_types_by_name['GetStatusResponse'] = _GETSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['GetResourceResponse'] = _GETRESOURCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'cluster.cluster_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.cluster.Request)
  ))
_sym_db.RegisterMessage(Request)

GetResourceRequest = _reflection.GeneratedProtocolMessageType('GetResourceRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRESOURCEREQUEST,
  __module__ = 'cluster.cluster_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.cluster.GetResourceRequest)
  ))
_sym_db.RegisterMessage(GetResourceRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'cluster.cluster_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.cluster.Response)
  ))
_sym_db.RegisterMessage(Response)

SubmitTaskResponse = _reflection.GeneratedProtocolMessageType('SubmitTaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITTASKRESPONSE,
  __module__ = 'cluster.cluster_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.cluster.SubmitTaskResponse)
  ))
_sym_db.RegisterMessage(SubmitTaskResponse)

GetStatusResponse = _reflection.GeneratedProtocolMessageType('GetStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATUSRESPONSE,
  __module__ = 'cluster.cluster_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.cluster.GetStatusResponse)
  ))
_sym_db.RegisterMessage(GetStatusResponse)

GetResourceResponse = _reflection.GeneratedProtocolMessageType('GetResourceResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRESOURCERESPONSE,
  __module__ = 'cluster.cluster_service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.cluster.GetResourceResponse)
  ))
_sym_db.RegisterMessage(GetResourceResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\032Microsoft.CGC.GRPC.Cluster'))

_CLUSTERPROXY = _descriptor.ServiceDescriptor(
  name='ClusterProxy',
  full_name='grpc.cluster.ClusterProxy',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=424,
  serialized_end=718,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetResource',
    full_name='grpc.cluster.ClusterProxy.GetResource',
    index=0,
    containing_service=None,
    input_type=_GETRESOURCEREQUEST,
    output_type=_GETRESOURCERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitTask',
    full_name='grpc.cluster.ClusterProxy.SubmitTask',
    index=1,
    containing_service=None,
    input_type=cluster_dot_task__pb2._TASK,
    output_type=_SUBMITTASKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='KillTask',
    full_name='grpc.cluster.ClusterProxy.KillTask',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='grpc.cluster.ClusterProxy.GetStatus',
    index=3,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_GETSTATUSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLUSTERPROXY)

DESCRIPTOR.services_by_name['ClusterProxy'] = _CLUSTERPROXY

# @@protoc_insertion_point(module_scope)
