# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import parameter_pb2 as parameter__pb2
import moduletype_pb2 as moduletype__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cluster/task.proto',
  package='cluster',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x63luster/task.proto\x12\x07\x63luster\x1a\x0fparameter.proto\x1a\x10moduletype.proto\"\xcb\x01\n\x04Task\x12\x30\n\x10input_parameters\x18\x01 \x03(\x0b\x32\x16.common.InputParameter\x12\x32\n\x11output_parameters\x18\x02 \x03(\x0b\x32\x17.common.OutputParameter\x12\x15\n\rsrc_code_path\x18\x03 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x04 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x05 \x01(\t\x12%\n\ttask_type\x18\x06 \x01(\x0e\x32\x12.common.ModuleTypeB\x18\xaa\x02\x15Microsoft.CGC.Clusterb\x06proto3')
  ,
  dependencies=[parameter__pb2.DESCRIPTOR,moduletype__pb2.DESCRIPTOR,])




_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='cluster.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_parameters', full_name='cluster.Task.input_parameters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_parameters', full_name='cluster.Task.output_parameters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_code_path', full_name='cluster.Task.src_code_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='cluster.Task.command', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='cluster.Task.config', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_type', full_name='cluster.Task.task_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=270,
)

_TASK.fields_by_name['input_parameters'].message_type = parameter__pb2._INPUTPARAMETER
_TASK.fields_by_name['output_parameters'].message_type = parameter__pb2._OUTPUTPARAMETER
_TASK.fields_by_name['task_type'].enum_type = moduletype__pb2._MODULETYPE
DESCRIPTOR.message_types_by_name['Task'] = _TASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'cluster.task_pb2'
  # @@protoc_insertion_point(class_scope:cluster.Task)
  ))
_sym_db.RegisterMessage(Task)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\025Microsoft.CGC.Cluster'))
# @@protoc_insertion_point(module_scope)
