// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authorizationservice.proto
// </auto-generated>
// Original file comments:
// Copyright (c) Microsoft. All rights reserved.
//
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Microsoft.CGC.DataAccess.GRPC {
  public static partial class AuthorizationService
  {
    static readonly string __ServiceName = "Microsoft.CGC.DataAccess.GRPC.AuthorizationService";

    static readonly grpc::Marshaller<global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest> __Marshaller_CheckPermissionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse> __Marshaller_CheckPermissionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest, global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse> __Method_CheckPermission = new grpc::Method<global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest, global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckPermission",
        __Marshaller_CheckPermissionRequest,
        __Marshaller_CheckPermissionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Microsoft.CGC.DataAccess.GRPC.AuthorizationserviceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AuthorizationService</summary>
    public abstract partial class AuthorizationServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse> CheckPermission(global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AuthorizationService</summary>
    public partial class AuthorizationServiceClient : grpc::ClientBase<AuthorizationServiceClient>
    {
      /// <summary>Creates a new client for AuthorizationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AuthorizationServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AuthorizationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AuthorizationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AuthorizationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AuthorizationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse CheckPermission(global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CheckPermission(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse CheckPermission(global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckPermission, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse> CheckPermissionAsync(global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CheckPermissionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionResponse> CheckPermissionAsync(global::Microsoft.CGC.DataAccess.GRPC.CheckPermissionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckPermission, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AuthorizationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AuthorizationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AuthorizationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CheckPermission, serviceImpl.CheckPermission).Build();
    }

  }
}
#endregion
