// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: workflowservice.proto
// </auto-generated>
// Original file comments:
// Copyright (c) Microsoft. All rights reserved.
//
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Microsoft.CGC.DataAccess.GRPC {
  public static partial class WorkflowService
  {
    static readonly string __ServiceName = "Microsoft.CGC.DataAccess.GRPC.WorkflowService";

    static readonly grpc::Marshaller<global::Microsoft.CGC.DataAccess.GRPC.Request> __Marshaller_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Microsoft.CGC.DataAccess.GRPC.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Microsoft.CGC.DataAccess.GRPC.Response> __Marshaller_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Microsoft.CGC.DataAccess.GRPC.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::Microsoft.CGC.DataAccess.GRPC.Request, global::Microsoft.CGC.DataAccess.GRPC.Response> __Method_Fun = new grpc::Method<global::Microsoft.CGC.DataAccess.GRPC.Request, global::Microsoft.CGC.DataAccess.GRPC.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Fun",
        __Marshaller_Request,
        __Marshaller_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Microsoft.CGC.DataAccess.GRPC.WorkflowserviceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WorkflowService</summary>
    public abstract partial class WorkflowServiceBase
    {
      /// <summary>
      /// rpc AddModule (Module) returns (AddOrUpdateEntityResponse);
      /// rpc GetModule (GetEntityRequest) returns (GetModuleResponse);
      /// rpc AddJob (Job) returns (AddOrUpdateEntityResponse);
      /// rpc GetJob (GetEntityRequest) returns (GetJobResponse);
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Microsoft.CGC.DataAccess.GRPC.Response> Fun(global::Microsoft.CGC.DataAccess.GRPC.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WorkflowService</summary>
    public partial class WorkflowServiceClient : grpc::ClientBase<WorkflowServiceClient>
    {
      /// <summary>Creates a new client for WorkflowService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WorkflowServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WorkflowService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WorkflowServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WorkflowServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WorkflowServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// rpc AddModule (Module) returns (AddOrUpdateEntityResponse);
      /// rpc GetModule (GetEntityRequest) returns (GetModuleResponse);
      /// rpc AddJob (Job) returns (AddOrUpdateEntityResponse);
      /// rpc GetJob (GetEntityRequest) returns (GetJobResponse);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Microsoft.CGC.DataAccess.GRPC.Response Fun(global::Microsoft.CGC.DataAccess.GRPC.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Fun(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// rpc AddModule (Module) returns (AddOrUpdateEntityResponse);
      /// rpc GetModule (GetEntityRequest) returns (GetModuleResponse);
      /// rpc AddJob (Job) returns (AddOrUpdateEntityResponse);
      /// rpc GetJob (GetEntityRequest) returns (GetJobResponse);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Microsoft.CGC.DataAccess.GRPC.Response Fun(global::Microsoft.CGC.DataAccess.GRPC.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Fun, null, options, request);
      }
      /// <summary>
      /// rpc AddModule (Module) returns (AddOrUpdateEntityResponse);
      /// rpc GetModule (GetEntityRequest) returns (GetModuleResponse);
      /// rpc AddJob (Job) returns (AddOrUpdateEntityResponse);
      /// rpc GetJob (GetEntityRequest) returns (GetJobResponse);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Microsoft.CGC.DataAccess.GRPC.Response> FunAsync(global::Microsoft.CGC.DataAccess.GRPC.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return FunAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// rpc AddModule (Module) returns (AddOrUpdateEntityResponse);
      /// rpc GetModule (GetEntityRequest) returns (GetModuleResponse);
      /// rpc AddJob (Job) returns (AddOrUpdateEntityResponse);
      /// rpc GetJob (GetEntityRequest) returns (GetJobResponse);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Microsoft.CGC.DataAccess.GRPC.Response> FunAsync(global::Microsoft.CGC.DataAccess.GRPC.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Fun, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WorkflowServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WorkflowServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WorkflowServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Fun, serviceImpl.Fun).Build();
    }

  }
}
#endregion
