FROM CENTOS:7.2.0
WORKDIR /sparkservice
ADD ~/script /sparkservice
RUN yum install -y java-1.8.0-openjdk
ENV JAVA_HOME $(readlink -f /usr/bin/java | sed "s:bin/java::") 
RUN wget http://ftp.jaist.ac.jp/pub/apache/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.6.tgz | tar -xvf -C /sparkservice/
RUN cd /sparkservice && ln -s spark-2.3.0-bin-hadoop2.6 spark
ENV SPARK_HOME /sparkservice/spark
ENV PATH $PATH:$SPARK_HOME/bin
RUN mkdir /sparkservice/hadoop_conf_dir
EVN HADOOP_CONF_DIR /sparkservice/hadoop_conf_dir