
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : job_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.CGC.Comm
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class Job
        : Entity
    {
        [global::Bond.Id(6), global::Bond.Type(typeof(string)), global::Bond.Required]
        public System.Guid ModuleId { get; set; }

        [global::Bond.Id(7)]
        public State JobState { get; set; }

        public Job()
            : this("Microsoft.CGC.Comm.Job", "Job")
        {}

        protected Job(string fullName, string name)
        {
            JobState = State.Unknown;
        }
    }
} // Microsoft.CGC.Comm
