
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : module_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.CGC.Comm
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class Module
        : Entity
    {
        [global::Bond.Id(6)]
        public string Configuration { get; set; }

        [global::Bond.Id(7)]
        public string CodePath { get; set; }

        [global::Bond.Id(8), global::Bond.Type(typeof(string))]
        public System.Guid FamilyId { get; set; }

        [global::Bond.Id(9)]
        public string Version { get; set; }

        [global::Bond.Id(10)]
        public List<ModuleParameter> Parameters { get; set; }

        public Module()
            : this("Microsoft.CGC.Comm.Module", "Module")
        {}

        protected Module(string fullName, string name)
        {
            Configuration = "";
            CodePath = "";
            FamilyId = new System.Guid();
            Version = "";
            Parameters = new List<ModuleParameter>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public enum ParameterDirection
    {
        None = unchecked((int)0),
        Input = unchecked((int)1),
        Output = unchecked((int)2),
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class ModuleParameter
    {
        [global::Bond.Id(0)]
        public bool IsGraphPort { get; set; }

        [global::Bond.Id(1)]
        public ParameterDirection Direction { get; set; }

        [global::Bond.Id(2)]
        public string ValueType { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public System.Guid PortId { get; set; }

        public ModuleParameter()
            : this("Microsoft.CGC.Comm.ModuleParameter", "ModuleParameter")
        {}

        protected ModuleParameter(string fullName, string name)
        {
            IsGraphPort = false;
            Direction = ParameterDirection.None;
        }
    }
} // Microsoft.CGC.Comm
