
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : userservice_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.CGC.Comm
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class PermissionCheckRequest
    {
        [global::Bond.Id(0)]
        public string Action { get; set; }

        [global::Bond.Id(1)]
        public string UserName { get; set; }

        [global::Bond.Id(2)]
        public string ResourceType { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(string))]
        public System.Guid ResourceId { get; set; }

        public PermissionCheckRequest()
            : this("Microsoft.CGC.Comm.PermissionCheckRequest", "PermissionCheckRequest")
        {}

        protected PermissionCheckRequest(string fullName, string name)
        {
            Action = "";
            UserName = "";
            ResourceType = "";
            ResourceId = new System.Guid();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class PermissionCheckResponse
    {
        [global::Bond.Id(0)]
        public bool HasPermission { get; set; }

        [global::Bond.Id(1)]
        public string Message { get; set; }

        public PermissionCheckResponse()
            : this("Microsoft.CGC.Comm.PermissionCheckResponse", "PermissionCheckResponse")
        {}

        protected PermissionCheckResponse(string fullName, string name)
        {
            Message = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class GetUsersRequest
    {
        [global::Bond.Id(0), global::Bond.Type(typeof(List<string>))]
        public List<System.Guid> UserIds { get; set; }

        [global::Bond.Id(1)]
        public List<string> UserNames { get; set; }

        [global::Bond.Id(2)]
        public List<string> GroupNames { get; set; }

        public GetUsersRequest()
            : this("Microsoft.CGC.Comm.GetUsersRequest", "GetUsersRequest")
        {}

        protected GetUsersRequest(string fullName, string name)
        {
            UserIds = new List<System.Guid>();
            UserNames = new List<string>();
            GroupNames = new List<string>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class GetUsersResponse
    {
        [global::Bond.Id(0)]
        public List<User> Users { get; set; }

        public GetUsersResponse()
            : this("Microsoft.CGC.Comm.GetUsersResponse", "GetUsersResponse")
        {}

        protected GetUsersResponse(string fullName, string name)
        {
            Users = new List<User>();
        }
    }
} // Microsoft.CGC.Comm
