
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : workflowservice_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.CGC.Comm
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class AddOrUpdateEntityResponse
    {
        [global::Bond.Id(0)]
        public bool AddedOrUpdated { get; set; }

        [global::Bond.Id(1), global::Bond.Type(typeof(string))]
        public System.Guid EntityId { get; set; }

        public AddOrUpdateEntityResponse()
            : this("Microsoft.CGC.Comm.AddOrUpdateEntityResponse", "AddOrUpdateEntityResponse")
        {}

        protected AddOrUpdateEntityResponse(string fullName, string name)
        {
            EntityId = new System.Guid();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class GetEntityRequest
    {
        [global::Bond.Id(0), global::Bond.Type(typeof(List<string>))]
        public List<System.Guid> EntityIds { get; set; }

        [global::Bond.Id(1)]
        public List<string> CreatedByUser { get; set; }

        public GetEntityRequest()
            : this("Microsoft.CGC.Comm.GetEntityRequest", "GetEntityRequest")
        {}

        protected GetEntityRequest(string fullName, string name)
        {
            EntityIds = new List<System.Guid>();
            CreatedByUser = new List<string>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class GetModuleResponse
    {
        [global::Bond.Id(0)]
        public List<Module> Modules { get; set; }

        public GetModuleResponse()
            : this("Microsoft.CGC.Comm.GetModuleResponse", "GetModuleResponse")
        {}

        protected GetModuleResponse(string fullName, string name)
        {
            Modules = new List<Module>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class GetExperimentResponse
    {
        [global::Bond.Id(0)]
        public List<Experiment> Experiments { get; set; }

        public GetExperimentResponse()
            : this("Microsoft.CGC.Comm.GetExperimentResponse", "GetExperimentResponse")
        {}

        protected GetExperimentResponse(string fullName, string name)
        {
            Experiments = new List<Experiment>();
        }
    }
} // Microsoft.CGC.Comm
