# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moduletype.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='moduletype.proto',
  package='common',
  syntax='proto3',
  serialized_pb=_b('\n\x10moduletype.proto\x12\x06\x63ommon*G\n\nModuleType\x12\x07\n\x03K8S\x10\x00\x12\r\n\tDOCKER_SM\x10\x01\x12\t\n\x05TF_SM\x10\x02\x12\x0b\n\x07TF_DIST\x10\x03\x12\t\n\x05SPARK\x10\x04\x42\x17\xaa\x02\x14Microsoft.CGC.Commonb\x06proto3')
)

_MODULETYPE = _descriptor.EnumDescriptor(
  name='ModuleType',
  full_name='common.ModuleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='K8S', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOCKER_SM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TF_SM', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TF_DIST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPARK', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=28,
  serialized_end=99,
)
_sym_db.RegisterEnumDescriptor(_MODULETYPE)

ModuleType = enum_type_wrapper.EnumTypeWrapper(_MODULETYPE)
K8S = 0
DOCKER_SM = 1
TF_SM = 2
TF_DIST = 3
SPARK = 4


DESCRIPTOR.enum_types_by_name['ModuleType'] = _MODULETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\024Microsoft.CGC.Common'))
# @@protoc_insertion_point(module_scope)
