# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobmanager/value_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jobmanager/value_type.proto',
  package='grpc.jobmanager',
  syntax='proto3',
  serialized_pb=_b('\n\x1bjobmanager/value_type.proto\x12\x0fgrpc.jobmanager*w\n\tValueType\x12\n\n\x06STRING\x10\x00\x12\t\n\x05INT32\x10\x01\x12\t\n\x05INT64\x10\x02\x12\n\n\x06SINGLE\x10\x03\x12\n\n\x06\x44OUBLE\x10\x04\x12\x0b\n\x07\x42OOLEAN\x10\x05\x12\x08\n\x04\x46ILE\x10\x06\x12\n\n\x06JTOKEN\x10\x07\x12\r\n\tDIRECTORY\x10\x08\x42 \xaa\x02\x1dMicrosoft.CGC.GRPC.JobManagerb\x06proto3')
)

_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='grpc.jobmanager.ValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT32', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT64', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOLEAN', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JTOKEN', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIRECTORY', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=48,
  serialized_end=167,
)
_sym_db.RegisterEnumDescriptor(_VALUETYPE)

ValueType = enum_type_wrapper.EnumTypeWrapper(_VALUETYPE)
STRING = 0
INT32 = 1
INT64 = 2
SINGLE = 3
DOUBLE = 4
BOOLEAN = 5
FILE = 6
JTOKEN = 7
DIRECTORY = 8


DESCRIPTOR.enum_types_by_name['ValueType'] = _VALUETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\035Microsoft.CGC.GRPC.JobManager'))
# @@protoc_insertion_point(module_scope)
