PROTODIR=../../proto/
PROTOC=$(PROTODIR)linux_x64/protoc
PROTOGRPC=$(PROTODIR)linux_x64/grpc_csharp_plugin

build:
	dotnet publish ./DataAccess.sln -c Release
    
restore:
	dotnet restore ./DataAccess.sln


