
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : graph_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.CGC.Comm
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class Graph
        : EntityBase
    {
        [global::Bond.Id(3)]
        public List<Node> Nodes { get; set; }

        [global::Bond.Id(4)]
        public List<Edge> Edges { get; set; }

        public Graph()
            : this("Microsoft.CGC.Comm.Graph", "Graph")
        {}

        protected Graph(string fullName, string name)
        {
            Nodes = new List<Node>();
            Edges = new List<Edge>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class Node
        : EntityBase
    {
        [global::Bond.Id(3)]
        public Layout Layout { get; set; }

        public Node()
            : this("Microsoft.CGC.Comm.Node", "Node")
        {}

        protected Node(string fullName, string name)
        {
            Layout = new Layout();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class Edge
        : EntityBase
    {
        [global::Bond.Id(3)]
        public Port FromPort { get; set; }

        [global::Bond.Id(4)]
        public Port ToPort { get; set; }

        public Edge()
            : this("Microsoft.CGC.Comm.Edge", "Edge")
        {}

        protected Edge(string fullName, string name)
        {
            FromPort = new Port();
            ToPort = new Port();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class Port
        : EntityBase
    {
        [global::Bond.Id(3), global::Bond.Type(typeof(string))]
        public System.Guid NodeId { get; set; }

        public Port()
            : this("Microsoft.CGC.Comm.Port", "Port")
        {}

        protected Port(string fullName, string name)
        {
            NodeId = new System.Guid();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class Layout
    {
        [global::Bond.Id(0)]
        public float X { get; set; }

        [global::Bond.Id(1)]
        public float Y { get; set; }

        [global::Bond.Id(2)]
        public float Width { get; set; }

        [global::Bond.Id(3)]
        public float Height { get; set; }

        public Layout()
            : this("Microsoft.CGC.Comm.Layout", "Layout")
        {}

        protected Layout(string fullName, string name)
        {
            
        }
    }
} // Microsoft.CGC.Comm
