
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : state_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Microsoft.CGC.Comm
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public enum State
    {
        Unknown = unchecked((int)0),
        New = unchecked((int)1),
        Running = unchecked((int)2),
        Aborting = unchecked((int)3),
        Aborted = unchecked((int)4),
        Failed = unchecked((int)5),
        PartialFailed = unchecked((int)6),
        Completed = unchecked((int)7),
    }
} // Microsoft.CGC.Comm
